version: "3.7"
services:
  traefik:
    image: "traefik:v2.9"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  minter:
    build:
      context: "."
    image: polyneme/minter
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - uvicorn
      - minter.entrypoints.fastapi_app:app
      - --reload
      - --host=0.0.0.0
      - --port=8000
    env_file:
      - .env
    ports:
      - "8888:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minter.rule=Host(`minter.test`)"
      - "traefik.http.routers.minter.entrypoints=web"
  mongo:
    image: mongo:4.4-bionic
    volumes:
      - fes_mongo_data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"


volumes:
  fes_mongo_data:
    driver: local