version: "3.7"
services:
  app:
    build:
      context: "."
    image: polyneme/minter
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - uvicorn
      - minter.entrypoints.fastapi_app:app
      - --reload
      - --host=0.0.0.0
      - --port=8000
    ports:
      - "8888:8000"