version: "3.7"
services:
  minter:
    build:
      context: "."
    image: polyneme/minter
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - uvicorn
      - minter.entrypoints.fastapi_app:app
      - --reload
      - --host=0.0.0.0
      - --port=8000
    env_file:
      - .env
    ports:
      - "8888:8000"
  mongo:
    image: mongo:4.4-bionic
    volumes:
      - fes_mongo_data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root


volumes:
  fes_mongo_data:
    driver: local